const Router = require('express').Router()
const UserRouter = require('./UserRouter.js')
const PetRouter = require('./PetRouter.js')
const UserRatingRouter = require('./UserRatingRouter.js')
const RatingRouter = require('./RatingRouter')
Router.use('/users', UserRouter)
Router.use('/pets', PetRouter)
Router.use('/userratings',UserRatingRouter)
Router.use('/ratings', RatingRouter)
module.exports = Router